"""Build a self-contained catalog page that uses actual runtime SVG files."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gunman Rush · 平原美术 Demo</title>
<style>*{box-sizing:border-box}body{margin:0;background:#101b22;color:#e8eadc;font:15px system-ui,sans-serif}main{max-width:1320px;margin:auto;padding:32px 24px}h1{margin:0 0 8px;font-size:30px}p{color:#a9b9b8;line-height:1.7}header{display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap}.badge{color:#f0c979;border:1px solid #75654a;padding:8px 14px;border-radius:20px}button,input,select{background:#21353c;color:#eff3e4;border:1px solid #486264;border-radius:8px;padding:10px;font:inherit}button{cursor:pointer}nav{display:flex;flex-wrap:wrap;gap:10px;margin:20px 0}canvas{width:100%;aspect-ratio:16/9;border:1px solid #3c5058;border-radius:12px;background:#97bbc5}#gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:12px}.card{border:1px solid #34484c;border-radius:10px;background:#18272e;padding:12px;min-width:0}.card img{width:100%;height:115px;object-fit:contain;background:repeating-conic-gradient(#23363d 0% 25%,#1c2c33 0% 50%) 50%/16px 16px;border-radius:6px}.card small{display:block;margin-top:8px;word-break:break-all;color:#b3c2bd}h2{margin-top:34px}.note{font-size:13px}#status{color:#f0c979}</style>
<main><header><div><h1>Gunman Rush · 平原美术 Demo</h1><p>统一角色与交互语言 · 模块化地形 · 独立背景层</p></div><span class="badge">Demo 候选 · 手机验收待完成</span></header>
<nav><label>种子 <input id="seed" type="number" value="1996" min="0" max="4294967295" style="width:130px"></label><button id="generate">重新拼装</button><button id="animate">暂停表现</button><label>角色动作 <select id="state"><option>idle</option><option>run</option><option>jump</option><option>fall</option><option>recoil</option><option>death</option></select></label><label><input id="safe" type="checkbox"> 显示落点保护区</label></nav>
<canvas id="scene" width="1280" height="720"></canvas><p class="note">这里展示真实 SVG 资源的视觉拼装、视差和动作表现。模块组合仅用于检查美术；未经过物理轨迹验证，不作为可通关随机地图。</p><p id="status"></p>
<h2>资源目录 <span id="count"></span></h2><nav><select id="filter"><option value="">全部</option><option>characters</option><option>terrain</option><option>props</option><option>backgrounds</option><option>objects</option><option>ui</option><option>vfx</option><option>enemies</option></select></nav><div id="gallery"></div></main>
<script>const manifest=__MANIFEST__;const assets=manifest.assets,images=new Map();let loaded=false,playing=true,t=0,last=0,platforms=[],seed=1996;const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');function rng(s){return()=>{s|=0;s=s+0x6D2B79F5|0;let x=Math.imul(s^s>>>15,1|s);x^=x+Math.imul(x^x>>>7,61|x);return((x^x>>>14)>>>0)/4294967296}}function get(name){return images.get(name)}function draw(name,x,y,w,h){const i=get(name);if(i)ctx.drawImage(i,x,y,w,h)}function tile(name,x,y,size=64){draw('assets/terrain/plains/'+name+'.svg',x,y-8,size,size)}function assemble(){seed=Number(document.querySelector('#seed').value)>>>0;const layout=rng(seed),dec=rng(seed^0x4a17b);platforms=[{x:0,y:540,n:5,v:1}];let x=410;for(let i=0;i<3;i++){platforms.push({x,y:420+Math.floor(layout()*3)*40,n:2+Math.floor(layout()*2),v:1+Math.floor(dec()*3)});x+=260}platforms.push({x:1150,y:540,n:3,v:1});t=0;document.querySelector('#status').textContent='Seed '+seed+' · '+assets.length+' 件资源 · 布局与装饰使用独立随机流'}
function character(x,y,state,time){ctx.save();ctx.translate(x,y);ctx.scale(.62,.62);let b=Math.sin(time*3.5)*.8,stride=0,tilt=0;if(state==='run'){stride=Math.sin(time*16)*.65;b=-Math.abs(Math.sin(time*16))*3}if(state==='jump'){stride=-.48;b=-3}if(state==='fall')stride=.25;if(state==='recoil'){tilt=-Math.exp(-(time%1)*16)*.17;b=-Math.exp(-(time%1)*16)*3}if(state==='death'){tilt=Math.min((time%1.5)*5,1.45);ctx.globalAlpha=Math.max(0,1-Math.max(time%1.5-.5,0)*2)}const p='assets/characters/courier/';ctx.save();ctx.translate(-8,-35+b);ctx.rotate(stride);draw(p+'leg.svg',-12,0,24,40);ctx.restore();ctx.save();ctx.translate(9,-35+b);ctx.rotate(-stride);draw(p+'leg.svg',-12,0,24,40);ctx.restore();ctx.save();ctx.rotate(tilt);draw(p+'scarf.svg',-65,-80+b,64,32);draw(p+'body.svg',-48,-112+b,96,96);ctx.restore();ctx.save();ctx.translate(4,-51+b);ctx.rotate(.45+Math.sin(time*.5)*.45);draw(p+'weapon_arm.svg',-4,-16,80,32);ctx.restore();ctx.restore()}
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(playing)t+=dt;ctx.clearRect(0,0,1280,720);if(loaded){const names=['plains_sky','plains_far_hills','plains_meadow','plains_distant_ruins'];names.forEach((n,k)=>{const offset=(t*(k+1)*2)%1280;draw('assets/backgrounds/plains/'+n+'.svg',-offset,0,1280,720);draw('assets/backgrounds/plains/'+n+'.svg',1280-offset,0,1280,720)});for(const p of platforms){for(let j=0;j<p.n;j++){const cap=j===0?'left':j===p.n-1?'right':'middle';tile('grass_'+cap+'_'+p.v,p.x+j*64,p.y);for(let r=1;p.y+r*64<760;r++)draw('assets/terrain/plains/rock_fill_'+p.v+'.svg',p.x+j*64,p.y-8+r*64,64,64)}if(document.querySelector('#safe').checked){ctx.fillStyle='#76e7df33';ctx.fillRect(p.x,p.y-48,p.n*64,48);ctx.strokeStyle='#8cf7ec';ctx.strokeRect(p.x,p.y-48,p.n*64,48)}}draw('assets/objects/moving_platform.svg',330+Math.sin(t)*15,560,128,32);ctx.save();ctx.translate(840,300);ctx.rotate(t*2);draw('assets/objects/saw_wheel.svg',-44,-44,88,88);ctx.restore();draw('assets/objects/shot_recharge_active.svg',640,335+Math.sin(t*2)*4,48,48);draw('assets/objects/jump_recharge_active.svg',445,330+Math.sin(t*2+1)*4,48,48);draw('assets/objects/checkpoint_active.svg',1190,460,48,80);draw('assets/enemies/plains/patrol_drone_idle.svg',925,390+Math.sin(t)*7,64,64);character(200,540,document.querySelector('#state').value,t);draw('assets/ui/control_move.svg',28,575,112,112);draw('assets/ui/control_aim.svg',1095,575,112,112);draw('assets/ui/control_jump.svg',985,600,80,80);draw('assets/ui/shot_resource.svg',25,25,32,32);draw('assets/ui/jump_resource.svg',25,65,32,32);for(let n=0;n<2;n++){ctx.fillStyle='#66e7f5';ctx.beginPath();ctx.arc(75+n*23,41,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd26a';ctx.beginPath();ctx.arc(75+n*23,81,6,0,Math.PI*2);ctx.fill()}}requestAnimationFrame(frame)}
function gallery(){const f=document.querySelector('#filter').value,list=assets.filter(a=>!f||a.path.startsWith('assets/'+f+'/'));document.querySelector('#count').textContent='('+assets.length+')';document.querySelector('#gallery').replaceChildren(...list.map(a=>{const box=document.createElement('div');box.className='card';const img=document.createElement('img');img.src='../'+a.path;img.loading='lazy';const label=document.createElement('small');label.textContent=a.id+' · '+a.width+'×'+a.height;box.append(img,label);return box}))}Promise.all(assets.filter(a=>a.path.endsWith('.svg')).map(a=>new Promise(resolve=>{const img=new Image();img.onload=()=>{images.set(a.path,img);resolve()};img.onerror=()=>{console.error('Missing image',a.path);resolve()};img.src='../'+a.path}))).then(()=>{loaded=true;assemble()});document.querySelector('#generate').onclick=assemble;document.querySelector('#animate').onclick=e=>{playing=!playing;e.target.textContent=playing?'暂停表现':'播放表现'};document.querySelector('#filter').onchange=gallery;gallery();requestAnimationFrame(frame);</script></html>'''

def build():
    manifest = json.loads((ROOT / 'assets/manifest.json').read_text())
    target = ROOT / 'preview'
    target.mkdir(exist_ok=True)
    (target / 'index.html').write_text(PAGE.replace('__MANIFEST__', json.dumps(manifest, ensure_ascii=False)))
    print('Preview: preview/index.html (open locally; no server required)')

if __name__ == '__main__':
    build()
