"""Preview untouched painted sources and their engine atlas regions."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]
PAGE=r'''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>风铃平原 · 手绘精修样板</title><style>*{box-sizing:border-box}body{margin:0;background:#122128;color:#f1efdf;font:15px system-ui}main{max-width:1320px;margin:auto;padding:30px 24px}h1{margin:0;font-size:30px}p{color:#b9c8c2;line-height:1.65}header{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.tag{border:1px solid #796b4b;color:#ead19a;border-radius:20px;padding:8px 16px}nav{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:18px 0}select,button{padding:10px;border-radius:8px;background:#29404a;color:#fff;border:1px solid #576c72;font:inherit}button{cursor:pointer}canvas{display:block;width:100%;aspect-ratio:16/9;background:#a2c7d4;border-radius:12px;border:1px solid #52676c}#gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}.card{border:1px solid #364b51;background:#1b2f37;padding:12px;border-radius:10px}.card img{width:100%;height:180px;object-fit:contain;background:repeating-conic-gradient(#34474b 0% 25%,#24373e 0% 50%) 50%/20px 20px;border-radius:7px}.card small{display:block;color:#b9c8c2;margin-top:8px;overflow-wrap:anywhere}h2{margin:30px 0 14px}.note{font-size:13px}#status{color:#efd498}</style><main><header><div><h1>风铃平原 · 手绘精修样板</h1><p>实际绘画贴图 · 人物动作帧 · 草岩、木桥与风铃维修站</p></div><span class="tag">视觉候选 / 尚待认可</span></header><nav><label>动作 <select id="state"><option>idle</option><option>run</option><option>jump</option><option>fall</option><option>recoil</option><option>death</option></select></label><button id="play">暂停动作</button><button id="flip">切换朝向</button><label><input id="hud" type="checkbox" checked> 显示 HUD</label><label><input id="old" type="checkbox"> 对比旧矢量画面</label></nav><canvas width="1280" height="720"></canvas><p id="status">载入绘画素材…</p><p class="note">这是一段固定几何的视觉样板，不是新关卡或全部随机地图验收。源图保持生成原样；动画使用纹理区域，未裁切或重绘 PNG。手绘平台与背景不默认无缝循环。</p><h2>本批原始绘画素材</h2><div id="gallery"></div></main><script>
const catalog=__CATALOG__,frames=catalog.frames||[],images=new Map();let ready=false,time=0,last=0,playing=true,facing=1;const cv=document.querySelector('canvas'),ctx=cv.getContext('2d');const paths=[...new Set(catalog.assets.map(a=>a.path).concat(['preview/plains_runtime_preview.png','assets/ui/control_move.svg','assets/ui/control_aim.svg','assets/ui/control_jump.svg','assets/objects/shot_recharge_active.svg','assets/objects/jump_recharge_active.svg']))];function image(p){return images.get(p)}function draw(p,x,y,w,h){const im=image(p);if(im)ctx.drawImage(im,x,y,w,h)}function cropped(p,x,y,w,h){const a=catalog.assets.find(a=>a.path===p),im=image(p);if(!a||!im)return;const b=a.opaque_bounds||[0,0,im.width,im.height];ctx.drawImage(im,b[0],b[1],b[2]-b[0],b[3]-b[1],x,y,w,h)}function platform(p,x,surface,w){const a=catalog.assets.find(a=>a.path===p);if(!a)return;const b=a.opaque_bounds,scale=w/(b[2]-b[0]),h=(b[3]-b[1])*scale,sy=p.includes('wood_bridge')?295:324;cropped(p,x,surface-(sy-b[1])*scale,w,h)}function character(){const state=document.querySelector('#state').value,fs=frames.filter(f=>f.state===state);if(!fs.length)return;const fps=state==='run'?10:state==='idle'?5:7;let index=Math.floor(time*fps);if(['jump','fall','recoil','death'].includes(state))index=Math.min(index,fs.length-1);else index%=fs.length;const f=fs[index],im=image(f.path);if(!im)return;const [x,y,w,h]=f.region,pivot=f.pivot_px,scale=catalog.character_scale||.1;ctx.save();ctx.translate(195,528);ctx.scale(facing*scale,scale);ctx.drawImage(im,x,y,w,h,-pivot[0],-pivot[1],w,h);ctx.restore()}
function render(now){const dt=Math.min((now-last)/1000,.05);last=now;if(playing)time+=dt;ctx.clearRect(0,0,1280,720);if(ready){if(document.querySelector('#old').checked){draw('preview/plains_runtime_preview.png',0,0,1280,720)}else{draw('assets/painterly_v2/background/sky.png',0,0,1280,720);draw('assets/painterly_v2/background/hills.png',0,0,1280,720);draw('assets/painterly_v2/background/meadow.png',0,0,1280,720);const ledge='assets/painterly_v2/terrain/grass_ledge.png';platform(ledge,-25,528,395);platform(ledge,690,450,220);platform(ledge,1060,531,300);platform('assets/painterly_v2/terrain/wood_bridge.png',435,446,185);ctx.save();ctx.translate(840,315);ctx.rotate(time*1.5);cropped('assets/painterly_v2/objects/saw.png',-48,-48,96,96);ctx.restore();cropped('assets/painterly_v2/objects/checkpoint.png',1135,447,58,84);cropped('assets/painterly_v2/objects/flowers.png',58,491,65,42);draw('assets/objects/shot_recharge_active.svg',655,339,44,44);draw('assets/objects/jump_recharge_active.svg',473,329,44,44);character();if(document.querySelector('#hud').checked){draw('assets/ui/control_move.svg',28,580,110,110);draw('assets/ui/control_aim.svg',1120,580,110,110);draw('assets/ui/control_jump.svg',1010,610,76,76)}}}requestAnimationFrame(render)}
const failures=[];Promise.all(paths.map(p=>new Promise(resolve=>{const im=new Image();im.onload=()=>{images.set(p,im);resolve()};im.onerror=()=>{failures.push(p);resolve()};im.src='../'+p}))).then(()=>{ready=true;document.querySelector('#status').textContent='本批 '+catalog.assets.length+' 张绘画源图 · '+frames.length+' 帧已登记'+(failures.length?' · 加载失败 '+failures.join(','):' · 全部图像已载入')});const gallery=document.querySelector('#gallery');catalog.assets.forEach(a=>{const c=document.createElement('div');c.className='card';const img=document.createElement('img');img.src='../'+a.path;img.loading='lazy';const label=document.createElement('small');label.textContent=a.path+' · '+a.width+'×'+a.height+' · '+a.status;c.append(img,label);gallery.append(c)});document.querySelector('#state').onchange=()=>time=0;document.querySelector('#play').onclick=e=>{playing=!playing;e.target.textContent=playing?'暂停动作':'播放动作'};document.querySelector('#flip').onclick=()=>facing*=-1;requestAnimationFrame(render);
</script></html>'''

if __name__=='__main__':
    data=json.loads((ROOT/'assets/painterly_v2/manifest.json').read_text())
    out=ROOT/'preview/painterly_v2.html'
    out.parent.mkdir(exist_ok=True)
    out.write_text(PAGE.replace('__CATALOG__',json.dumps(data,ensure_ascii=False)),encoding='utf-8')
    print(out.relative_to(ROOT))
